# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k-9e9eDFkzqD6Uhnz1UeC-NHFqNwJxCq

## Business Problem

A factory produces two products: **Product A** and **Product B**.

Each product provides profit and consumes limited resources such as labor hours
and machine hours.

The goal is to **maximize total profit** while satisfying all resource constraints.

## Business Problem

A factory produces two products: **Product A** and **Product B**.

Each product provides profit and consumes limited resources such as labor hours
and machine hours.

The goal is to **maximize total profit** while satisfying all resource constraints.
"""

import pulp
# Create a maximization problem
model = pulp.LpProblem("Profit_Maximization", pulp.LpMaximize)
# Decision variables
A = pulp.LpVariable('Product_A', lowBound=0)
B = pulp.LpVariable('Product_B', lowBound=0)
# Objective function: Maximize profit
model += 40 * A + 30 * B

# Labor constraint
model += 2 * A + 1 * B <= 100

# Machine constraint
model += 1 * A + 2 * B <= 80
model.solve()

print("Status:", pulp.LpStatus[model.status])

print("Optimal Production Quantities:")
print("Product A:", A.varValue)
print("Product B:", B.varValue)

print("Maximum Profit: ₹", pulp.value(model.objective))

"""## Insights

- The optimal production plan is to produce **40 units of Product A** and
  **20 units of Product B**.
- This plan utilizes the available labor and machine resources efficiently.
- The maximum achievable profit is **₹2200**.
- Linear Programming helps businesses make data-driven and optimal decisions.

## Insights

- The optimal production plan is to produce **40 units of Product A** and
  **20 units of Product B**.
- This plan utilizes the available labor and machine resources efficiently.
- The maximum achievable profit is **₹2200**.
- Linear Programming helps businesses make data-driven and optimal decisions.

## Conclusion

This project demonstrates the use of Linear Programming to solve a real-world
business optimization problem.

By using Python and PuLP, we were able to:
- Define decision variables
- Set constraints
- Maximize profit
- Extract actionable business insights
"""